nodeLinker: node-modules

enableGlobalCache: true

logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard
  - code: YN0006 # SOFT_LINK_BUILD
    level: discard
  - code: YN0076 # INCOMPATIBLE_PEER_VERSION
    level: discard

packageExtensions:
  "@backstage/core-components@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
  "@backstage/core-plugin-api@*":
    peerDependencies:
      "@types/react": "*"
  "@backstage/plugin-catalog-react@*":
    peerDependencies:
      "@types/react": "*"
  "@backstage/plugin-permission-react@*":
    peerDependencies:
      "@types/react": "*"
