nodeLinker: node-modules

enableGlobalCache: true

logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard
  - code: YN0006 # SOFT_LINK_BUILD
    level: discard
  - code: YN0076 # INCOMPATIBLE_PEER_VERSION
    level: discard

packageExtensions:
  "@backstage/core-components@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
  "@backstage/core-plugin-api@*":
    peerDependencies:
      "@types/react": "*"
  "@backstage/plugin-catalog-react@*":
    peerDependencies:
      "@types/react": "*"
  "@backstage/plugin-permission-react@*":
    peerDependencies:
      "@types/react": "*"

plugins:
  - checksum: 254c816a15098e2a0b414345caf9144409fbf6a63da7ec8ec8d3454aa1d2edfbbc32cd264d8c464b7ec4aca7809c690848a7c1191b5f8167dec81dbdf6107b01
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.35.0-next.2/yarn-plugin'